### ISSUE TITLE
Create configurable mandatory JIRA fields

### ISSUE THREAD

**Issue by dominic-martino** [ThoughtsLive/jira-steps#1]
In the class 'org.thoughtslive.jenkins.plugins.jira.steps.NewIssueStep' the logic for verifying a JIRA ticket before created has hardcoded logic.

```java
@Override
    protected <T> ResponseData<T> verifyInput() throws Exception {
      String errorMessage = null;
      ResponseData<T> response = verifyCommon(step);

      if (response == null) {
        final IssueInput issue = step.getIssue();

        if (issue == null) {
          errorMessage = "issue is null.";
          return buildErrorResponse(new RuntimeException(errorMessage));
        }

        if (issue.getFields() == null) {
          errorMessage = "fields is null.";
          return buildErrorResponse(new RuntimeException(errorMessage));
        }

        if (Util.fixEmpty(issue.getFields().get("summary").toString()) == null) {
          errorMessage = "fields->summary is empty or null.";
        }

        if (Util.fixEmpty(issue.getFields().get("description").toString()) == null) {
          errorMessage = "fields->description is empty or null.";
        }

        if (issue.getFields().get("issuetype") == null) {
          errorMessage = "fields->issuetype is null.";
          return buildErrorResponse(new RuntimeException(errorMessage));

        }

        if (issue.getFields().get("project") == null) {
          errorMessage = "fields->project is null.";
          return buildErrorResponse(new RuntimeException(errorMessage));
        }

        if (errorMessage != null) {
          response = buildErrorResponse(new RuntimeException(errorMessage));
        }
      }
      return response;
    }
  }
```

This assumes some fields are mandatory within JIRA, which may not always be the case, description for example is the one in our particular use case. The intended fix would be to allow the fields to be configurable within Jenkins. 

We are using the latest version (1.2.0) of the jira-steps plugin

**Comment by dominic-martino** [comment]
I have created a fork and intend to contribute a solution to this, I have created issue to give some visibility and open a dialog on the fix.

**Comment by nrayapati** [comment]
This repo has been deprecated with the one in jenkinsci. Refer to the https://github.com/ThoughtsLive/jira-steps/blob/master/README.adoc. 

If we need to log something to jira-steps-plugin plugin. please use jenkins jira queue. https://github.com/jenkinsci/jira-steps-plugin#disclaimer

**Comment by nrayapati** [comment]
Though the description is optional, I don't think a reason when we create a one without description, if you don't want to have a any description, just add a single character (or some message that I don't have description) to avoid this issue. I am going to get ride of all these validations soon, and will leave that job to JIRA though. 

Probably "NA", " ", "TODO" something like that.

**Comment by dominic-martino** [comment]
Thanks for getting back to me Naresh, we have got a JIRA system which we are trying to integrate with where everything which is required in the JIRA ticket has its own custom field. The description is not needed as the custom fields cater for all the information required which is then validated separately. Having all this information in the description would make it very hard to validate as many of the values are enumerated values. Do you have any timescales for getting rid of the validation and letting JIRA handle it?

**Comment by dominic-martino** [comment]
FYI - some of the links in the contributing guide are pointing to the old repo hence I picked up the deprecated project by mistake :)

**Comment by nrayapati** [comment]
Sorry for the inconvenience there, probably this weekend when I get some free time.

**Comment by nrayapati** [comment]
@dominic-martino  Released 1.2.1, relaxed few steps input validation and also updated documentation. Thanks for your interest.

**Comment by dominic-martino** [comment]
Naresh, really appreciate you picking this up so quickly. I will have a look at 1.2.1.

**Comment by dominic-martino** [comment]
Looked at 1.2.1 hit a null pointer exception which I have raised a ticket for here - https://issues.jenkins-ci.org/browse/JENKINS-44817
